import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useAuth } from '../lib/auth'
import { Alert } from '@mui/material'
import { Activity, Database, MessageSquareText, Users } from 'lucide-react'
import { api } from '../lib/api'
import { Heading } from '../components/Layout'

type Analytics={users:number;uploads:number;queries:number;indexed_chunks:number;estimated_tokens:number;recent_errors:{file_id:string;error:string}[];audit:{event:string;target_id:string;created_at:string}[]}
type Account={id:string;email:string;role:string;created_at:string}
export default function Admin(){const client=useQueryClient();const me=useAuth(s=>s.user);const updateRole=async(u:Account)=>{if(u.id===me?.id)return;const target=u.role==='admin'?'user':'admin';if(!confirm(`Set ${u.email} to ${target}?`))return;await api.patch(`/admin/users/${u.id}/role`,null,{params:{role_name:target}});client.invalidateQueries({queryKey:['admin-users']})};const {data,error}=useQuery<Analytics>({queryKey:['admin-analytics'],queryFn:async()=>(await api.get('/admin/analytics')).data});const {data:users=[]}=useQuery<Account[]>({queryKey:['admin-users'],queryFn:async()=>(await api.get('/admin/users')).data});const stats=[['Users',data?.users,Users],['Uploads',data?.uploads,Database],['Queries',data?.queries,MessageSquareText],['Indexed chunks',data?.indexed_chunks,Activity],['Estimated tokens',data?.estimated_tokens,Activity]] as const;return <><Heading eyebrow="Administration" title="System overview" description="Aggregate usage, indexing failures, user roles, and audit events."/>{error&&<Alert severity="error">Could not load admin analytics.</Alert>}<div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{stats.map(([label,value,Icon])=><div className="surface p-5" key={label}><Icon className="text-teal-300" size={20}/><p className="text-3xl font-bold mt-5">{value??'…'}</p><p className="muted text-sm mt-1">{label}</p></div>)}</div><div className="grid lg:grid-cols-2 gap-5 mt-6"><section className="surface p-6"><h2 className="font-bold text-lg mb-4">Accounts</h2><div className="space-y-2 max-h-100 overflow-y-auto">{users.map(u=><div className="raised p-3 flex justify-between gap-2" key={u.id}><span className="truncate text-sm">{u.email}</span><div className="flex gap-2 items-center"><span className="tag">{u.role}</span>{u.id!==me?.id&&<button className="outline !p-1 text-xs" onClick={()=>updateRole(u)}>Change</button>}</div></div>)}</div></section><section className="surface p-6"><h2 className="font-bold text-lg mb-4">Recent events</h2><div className="space-y-2 max-h-100 overflow-y-auto">{data?.audit.map((a,i)=><div className="raised p-3 flex justify-between text-sm gap-3" key={i}><span>{a.event}</span><span className="muted">{new Date(a.created_at).toLocaleString()}</span></div>)}{!data?.audit.length&&<p className="muted text-sm">No events yet.</p>}</div></section></div><section className="surface p-6 mt-5"><h2 className="font-bold text-lg mb-4">Processing errors</h2>{data?.recent_errors.length?data.recent_errors.map(e=><div className="raised p-3 text-sm mb-2" key={e.file_id}><span className="muted">{e.file_id}</span><p className="text-red-400 mt-1">{e.error}</p></div>):<p className="muted text-sm">No failed files.</p>}</section></>}
