import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Alert, CircularProgress } from '@mui/material'
import { BookOpen, LockKeyhole } from 'lucide-react'
import { api, errorText } from '../lib/api'
import { useAuth } from '../lib/auth'

export default function Auth({mode}:{mode:'login'|'register'}) {
  const navigate = useNavigate(); const setTokens = useAuth(s => s.setTokens)
  const [email,setEmail] = useState(''); const [password,setPassword] = useState(''); const [busy,setBusy] = useState(false); const [error,setError] = useState('')
  const submit = async (event:FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const {data} = await api.post(`/auth/${mode}`, {email,password}); setTokens(data.access_token,data.refresh_token,data.user); navigate('/app') } catch(e) { setError(errorText(e)) } finally {setBusy(false)} }
  return <div className="min-h-screen grid lg:grid-cols-2"><div className="hidden lg:flex flex-col justify-between p-12 bg-[#0c2032] relative overflow-hidden"><Link to="/" className="text-2xl font-black">ATLAS<span className="text-teal-300">.</span></Link><div className="absolute w-120 h-120 rounded-full bg-teal-300/15 blur-[100px] left-1/3 top-1/4"/><div className="relative"><BookOpen size={43} className="text-teal-300 mb-7"/><h2 className="text-5xl font-bold max-w-lg leading-tight">Turn scattered files into connected knowledge.</h2><p className="muted mt-7 text-lg max-w-md">A single private workspace for evidence-driven research and enterprise search.</p></div><p className="muted text-sm">© 2026 Atlas Document Intelligence</p></div><div className="flex items-center justify-center p-6"><div className="w-full max-w-md"><Link to="/" className="lg:hidden text-2xl font-black">ATLAS<span className="text-teal-300">.</span></Link><div className="w-13 h-13 rounded-xl bg-teal-300/15 text-teal-300 grid place-items-center mt-9 lg:mt-0 mb-6"><LockKeyhole/></div><h1 className="text-3xl font-bold">{mode==='login' ? 'Welcome back' : 'Start your workspace'}</h1><p className="muted mt-3">{mode==='login' ? 'Sign in to continue your research.' : 'Create a private account to index your sources.'}</p><form onSubmit={submit} className="mt-9 space-y-5"><label className="block text-sm">Email address<input className="field mt-2" autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm">Password<input className="field mt-2" autoComplete={mode==='register'?'new-password':'current-password'} type="password" minLength={mode==='register'?12:1} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='register' && <p className="muted text-xs">Use at least 12 characters. New accounts have the User role.</p>}{error && <Alert severity="error">{error}</Alert>}<button disabled={busy} className="action w-full h-12 flex items-center justify-center gap-2">{busy && <CircularProgress size={18}/>} {mode==='login'?'Sign in':'Create account'}</button></form><p className="muted mt-7 text-sm">{mode==='login' ? 'New to Atlas?' : 'Already registered?'} <Link className="text-teal-300 font-semibold" to={mode==='login'?'/register':'/login'}>{mode==='login'?'Create an account':'Sign in'}</Link></p></div></div></div>
}
