import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { ArrowUpRight, Database, FileCheck2, MessageSquareText, UploadCloud, Activity } from 'lucide-react'
import { api } from '../lib/api'
import { Empty, Heading } from '../components/Layout'

type Overview = { files:number;ready:number;queries:number;estimated_tokens:number;file_types:Record<string,number>;recent:{name:string;status:string;created_at:string}[] }
export default function Dashboard() {
  const {data, isLoading, error} = useQuery<Overview>({queryKey:['dashboard'], queryFn:async()=> (await api.get('/dashboard')).data})
  const stats = [{label:'Total files',value:data?.files??0,icon:Database},{label:'Indexed files',value:data?.ready??0,icon:FileCheck2},{label:'Queries asked',value:data?.queries??0,icon:MessageSquareText},{label:'Estimated tokens',value:data?.estimated_tokens??0,icon:Activity}]
  const chart = Object.entries(data?.file_types || {}).map(([name,count])=>({name:name.toUpperCase(),count}))
  return <><Heading eyebrow="Workspace overview" title="Good to see you." description="Your knowledge base, activity, and next steps in one place."><Link to="/app/upload" className="action flex items-center gap-2"><UploadCloud size={17}/> Upload files</Link></Heading>{error && <p className="text-red-400 mb-6">Could not load dashboard.</p>}
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-5">{stats.map(({label,value,icon:Icon})=><div className="surface p-6" key={label}><div className="flex justify-between"><span className="muted text-sm">{label}</span><Icon className="text-teal-300" size={20}/></div><p className="text-4xl font-bold mt-6">{isLoading?'…':value}</p><p className="muted text-xs mt-2">In your private workspace</p></div>)}</div>
    <div className="grid lg:grid-cols-[1.3fr_1fr] gap-5 mt-6"><section className="surface p-6"><div className="flex justify-between mb-7"><div><h2 className="font-bold text-lg">Knowledge mix</h2><p className="muted text-sm mt-1">Indexed and pending file types</p></div><span className="tag">FILES</span></div>{chart.length?<ResponsiveContainer width="100%" height={250}><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#56dfc1" stopOpacity={.45}/><stop offset="95%" stopColor="#56dfc1" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#334155" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="name" stroke="#94a3b8"/><Tooltip contentStyle={{background:'#15233a',border:'1px solid #334155',borderRadius:12}}/><Area type="monotone" dataKey="count" stroke="#56dfc1" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer>:<div className="grid place-items-center h-60 muted">Upload files to populate this chart.</div>}</section><section className="surface p-6"><h2 className="font-bold text-lg">Recent activity</h2><p className="muted text-sm mt-1 mb-5">Latest uploads and processing states</p>{data?.recent.length ? <div className="space-y-3">{data.recent.map((item,i)=><div className="raised p-3 flex items-center gap-3" key={i}><span className="w-9 h-9 rounded-lg bg-teal-300/12 grid place-items-center text-teal-300"><Database size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name}</p><p className="muted text-xs">{new Date(item.created_at).toLocaleDateString()}</p></div><span className="tag">{item.status}</span></div>)}</div>:<p className="muted mt-16 text-center">No uploads yet.</p>}</section></div>
    <div className="grid md:grid-cols-2 gap-5 mt-6"><Link to="/app/chat" className="surface p-6 flex items-center justify-between hover:border-teal-300/50 transition"><div><h3 className="font-bold text-lg">Ask your documents</h3><p className="muted mt-2 text-sm">Get an answer with linked evidence.</p></div><ArrowUpRight className="text-teal-300"/></Link><Link to="/app/search" className="surface p-6 flex items-center justify-between hover:border-teal-300/50 transition"><div><h3 className="font-bold text-lg">Find a source</h3><p className="muted mt-2 text-sm">Search across all indexed content.</p></div><ArrowUpRight className="text-teal-300"/></Link></div>{!data && !isLoading && !error && <Empty title="No activity" detail="Start with your first upload."/>}</>
}
