import { useState, type FormEvent } from 'react'
import { Alert, CircularProgress } from '@mui/material'
import { ExternalLink, Search as SearchIcon } from 'lucide-react'
import { api, errorText, previewFile } from '../lib/api'
import { Empty, Heading } from '../components/Layout'
import type { Citation } from '../lib/types'

export default function Search() {
  const [q,setQ]=useState(''),[kind,setKind]=useState(''),[date,setDate]=useState(''),[tag,setTag]=useState(''),[hits,setHits]=useState<Citation[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const search=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await api.get('/search',{params:{q,file_type:kind||undefined,date_from:date||undefined,tag:tag||undefined,top_k:20}});setHits(data)}catch(err){setError(errorText(err))}finally{setBusy(false)}}
  return <><Heading eyebrow="Enterprise search" title="Find what matters" description="Search indexed passages, then open the original file for context."/><form className="surface p-5" onSubmit={search}><div className="flex gap-3"><div className="relative flex-1"><SearchIcon className="absolute top-3.5 left-3 muted" size={18}/><input className="field !pl-10" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search across your documents, media and logs" minLength={2} required/></div><button className="action flex items-center gap-2" disabled={busy}>{busy&&<CircularProgress size={17}/>} Search</button></div><div className="grid sm:grid-cols-3 gap-3 mt-4"><label className="text-xs muted">File type<select className="field mt-1" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option>{['pdf','docx','pptx','xlsx','csv','png','jpg','mp3','wav','mp4','json','log','txt'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs muted">Uploaded since<input type="date" className="field mt-1" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="text-xs muted">Tag<input className="field mt-1" placeholder="Optional tag" value={tag} onChange={e=>setTag(e.target.value)}/></label></div></form>{error&&<Alert severity="error" className="mt-5">{error}</Alert>}{hits!==null&&<div className="mt-8"><h2 className="font-bold text-lg mb-5">{hits.length} matching passage{hits.length===1?'':'s'}</h2>{hits.length?<div className="space-y-4">{hits.map(hit=><div className="surface p-5" key={hit.chunk_id}><div className="flex flex-wrap gap-3 justify-between"><div><span className="tag">{hit.modality||'text'}</span><h3 className="font-semibold mt-3">{hit.file_name} <span className="muted text-sm font-normal">· {hit.location}</span></h3></div><button className="outline flex gap-2 items-center text-sm" onClick={()=>previewFile(hit.file_id).catch(e=>setError(errorText(e)))}>Open source <ExternalLink size={15}/></button></div><p className="muted text-sm leading-7 mt-4 whitespace-pre-wrap line-clamp-5">{hit.excerpt}</p><p className="muted text-xs mt-4">Retrieval signal (not calibrated): {hit.score.toFixed(3)} · passage {hit.number}</p></div>)}</div>:<Empty title="No matches" detail="Try broader terms or remove a filter."/>}</div>}{hits===null&&<div className="mt-8"><Empty title="Search your knowledge base" detail="Type at least two characters to find matching source passages."/></div>}</>
}
