import { useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, LinearProgress } from '@mui/material'
import { FileText, RefreshCw, Trash2, UploadCloud, ExternalLink, Tag } from 'lucide-react'
import { api, errorText, previewFile } from '../lib/api'
import { Empty, Heading } from '../components/Layout'
import type { StoredFile } from '../lib/types'

export default function Upload() {
  const input = useRef<HTMLInputElement>(null), client = useQueryClient()
  const [drag,setDrag] = useState(false), [method,setMethod] = useState('document'), [message,setMessage] = useState(''), [failure,setFailure] = useState('')
  const {data:files=[],isLoading} = useQuery<StoredFile[]>({queryKey:['files'],queryFn:async()=> (await api.get('/files/list')).data,refetchInterval:3000})
  const upload = useMutation({mutationFn:async (selected:FileList|File[])=> { let duplicates=0; for (const file of Array.from(selected)) { const body=new FormData(); body.append('file',file); body.append('chunk_method',method); const response=await api.post('/files/upload',body); if(response.data.duplicate) duplicates++ } return duplicates },onSuccess:dups=>{client.invalidateQueries({queryKey:['files']});client.invalidateQueries({queryKey:['dashboard']});setMessage(dups?`Uploaded. ${dups} duplicate file(s) reused.`:'Upload accepted. Indexing will begin shortly.');setFailure('')},onError:e=>setFailure(errorText(e))})
  const remove = async (id:string) => { if(!window.confirm('Delete this file and its indexed content?')) return; try {await api.delete(`/files/${id}`);client.invalidateQueries({queryKey:['files']});client.invalidateQueries({queryKey:['dashboard']})} catch(e){setFailure(errorText(e))} }
  const editTags = async (file:StoredFile) => { const input=window.prompt('Tags, separated by commas',file.tags);if(input===null)return;try{await api.patch(`/files/${file.id}/tags`,input.split(',').map(x=>x.trim()).filter(Boolean));client.invalidateQueries({queryKey:['files']})}catch(e){setFailure(errorText(e))} }
  const retry = async (id:string) => {try{await api.post(`/files/${id}/process?chunk_method=${method}`);client.invalidateQueries({queryKey:['files']})}catch(e){setFailure(errorText(e))}}
  return <><Heading eyebrow="Source library" title="Upload center" description="Add sources to your private workspace. Indexing status updates automatically."/>
    <div className="grid lg:grid-cols-[1.5fr_1fr] gap-5"><div className={`surface border-dashed border-2 p-10 text-center transition ${drag?'!border-teal-300 bg-teal-300/5':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files.length) upload.mutate(e.dataTransfer.files)}}><div className="w-18 h-18 mx-auto rounded-2xl bg-teal-300/12 text-teal-300 grid place-items-center mb-5"><UploadCloud size={32}/></div><h2 className="text-xl font-bold">Drop your files here</h2><p className="muted text-sm mt-2">or choose files from your device</p><input ref={input} type="file" multiple className="hidden" accept=".pdf,.docx,.pptx,.xlsx,.csv,.png,.jpg,.jpeg,.webp,.mp3,.wav,.m4a,.mp4,.mov,.txt,.log,.json,.jsonl" onChange={e=>{if(e.target.files?.length) upload.mutate(e.target.files);e.target.value=''}}/><button className="action mt-6" onClick={()=>input.current?.click()} disabled={upload.isPending}>Browse files</button><p className="muted text-xs mt-5">PDF, Office, images, audio, video, text, logs · up to 30 MB by default</p>{upload.isPending && <LinearProgress className="mt-5"/>}</div><div className="surface p-7"><h3 className="font-bold text-lg mb-3">Indexing options</h3><p className="muted text-sm mb-5">Choose how text is split before embedding. Tables stay together.</p><label className="text-sm">Chunking strategy<select className="field mt-2" value={method} onChange={e=>setMethod(e.target.value)}><option value="document">Document aware</option><option value="recursive">Recursive</option><option value="fixed">Fixed</option><option value="semantic">Semantic</option></select></label><div className="raised p-4 mt-5 text-sm"><p className="font-medium">Processing path</p><p className="muted mt-2 leading-6">Extract → OCR or transcription → chunk → embed → index → cite</p></div></div></div>
    {message && <Alert severity="success" className="mt-5" onClose={()=>setMessage('')}>{message}</Alert>}{failure && <Alert severity="error" className="mt-5" onClose={()=>setFailure('')}>{failure}</Alert>}
    <div className="flex items-center justify-between mt-10 mb-4"><h2 className="text-xl font-bold">Your sources <span className="muted font-normal">({files.length})</span></h2><span className="muted text-sm">Updates every 3 seconds</span></div>{!isLoading && !files.length ? <Empty title="No files yet" detail="Upload a source to start building your knowledge base."/> : <div className="surface overflow-hidden"><div className="divide-y" style={{borderColor:'var(--line)'}}>{files.map(file=><div key={file.id} className="flex flex-wrap items-center gap-4 p-4 md:px-6 border-b last:border-b-0" style={{borderColor:'var(--line)'}}><div className="w-11 h-11 rounded-xl bg-indigo-400/12 text-indigo-300 grid place-items-center"><FileText size={21}/></div><div className="flex-1 min-w-45"><p className="font-medium truncate">{file.name}</p><p className="muted text-xs mt-1">{(file.size/1024).toFixed(1)} KB · {new Date(file.created_at).toLocaleString()}</p>{file.error && <p className="text-red-400 text-xs mt-1">{file.error}</p>}</div><button className="outline !p-2" onClick={()=>editTags(file)} title={`Edit tags: ${file.tags}`} aria-label={`Edit tags for ${file.name}`}><Tag size={17}/></button><span className={`tag ${file.status==='failed'?'!text-red-400 !border-red-400/30':''}`}>{file.status}</span><button className="outline !p-2" onClick={()=>previewFile(file.id).catch(e=>setFailure(errorText(e)))} aria-label={`Preview ${file.name}`}><ExternalLink size={17}/></button>{file.status==='failed' && <button className="outline !p-2" onClick={()=>retry(file.id)} aria-label={`Retry ${file.name}`}><RefreshCw size={17}/></button>}<button className="outline !p-2 hover:!text-red-400" onClick={()=>remove(file.id)} aria-label={`Delete ${file.name}`}><Trash2 size={17}/></button></div>)}</div></div>}</>
}
